version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tapaz
      - MYSQL_USER=tapaz
      - MYSQL_PASSWORD=password
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql_data_folder:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

  tapaz:
    build: .
    links:
      - mysql
    container_name: tapaz
    depends_on: 
      - mysql
    command: python tapaz.py
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment: 
      - PMA_HOST=mysql
    depends_on: 
      - mysql
    links: 
      - mysql
    ports: 
      - 8080:80
  
  adminer:
    image: adminer
    container_name: adminer
    environment: 
      - ADMINER_DESIGN=nette
    depends_on: 
      - mysql
    links: 
      - mysql
    ports: 
      - 8090:8080